version: "3"

services:
    routera:
        build: .
        network_mode: "host"
        command: tail -f /dev/null
    routerb:
        build: .
        network_mode: "host"
        command: tail -f /dev/null
    routerc:
        build: .
        network_mode: "host"
        command: tail -f /dev/null
    routerd:
        build: .
        network_mode: "host"
        command: tail -f /dev/null
    routere:
        build: .
        network_mode: "host"
        command: tail -f /dev/null
        
