version: "3"

services:
    routera:
        container_name: router_a
        build: .
        networks:
            testing_net:
                ipv4_address: 172.28.1.1
        stdin_open: true
    routerb:
        container_name: router_b
        build: .
        networks:
            testing_net:
                ipv4_address: 172.28.1.2
        stdin_open: true
    routerc:
        container_name: router_c
        build: .
        networks:
            testing_net:
                ipv4_address: 172.28.1.3
        stdin_open: true
    routerd:
        container_name: router_d
        build: .
        networks:
            testing_net:
                ipv4_address: 172.28.1.4
        stdin_open: true
    routere:
        container_name: router_e
        build: .
        networks:
            testing_net:
                ipv4_address: 172.28.1.5
        stdin_open: true

networks:
    testing_net:
        ipam:
            driver: default
            config:
                - subnet: 172.28.0.0/16
